# 多能谱源 (Multi-energy Source) - 多个能量峰
/run/initialize
/gps/particle gamma
/gps/energy 0.0595 MeV
/gps/ene/type Arb
/gps/hist/type arb
/gps/hist/point 0.030 0.0
/gps/hist/point 0.0595 1.0
/gps/hist/point 0.080 0.0
/gps/hist/point 0.100 0.0
/gps/hist/point 0.200 0.0
/gps/hist/inter Lin
/gps/pos/type Surface
/gps/pos/shape Circle
/gps/pos/radius 2.0 cm
/gps/pos/centre 0 0 -30 cm
/gps/ang/type iso
/gps/ang/mintheta 0 deg
/gps/ang/maxtheta 30 deg
/run/beamOn 10000